# Generated by Django 5.0.1 on 2024-01-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.IntegerField()),
                ('page_no', models.IntegerField()),
                ('year', models.CharField(max_length=20)),
                ('continuos_number', models.IntegerField(unique=True)),
                ('archive_no', models.IntegerField()),
                ('branch_no', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('Surrender_name', models.CharField(max_length=200)),
                ('Surrender_date', models.DateField()),
                ('register_number', models.IntegerField()),
                ('remarks', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='records/images')),
            ],
        ),
    ]
