# Generated by Django 5.0.1 on 2024-01-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.IntegerField()),
                ('page_no', models.IntegerField()),
                ('year', models.CharField(max_length=20)),
                ('continuos_number', models.IntegerField(unique=True)),
                ('archive_no', models.IntegerField()),
                ('branch_no', models.IntegerField()),
                ('short_explain', models.TextField()),
            ],
        ),
    ]
