# Generated by Django 5.0.1 on 2024-01-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_archive_no_outgoingdoc_dossier_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoingdoc',
            old_name='continuos_number',
            new_name='continuos_num',
        ),
    ]
