# Generated by Django 5.0.1 on 2024-01-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_continuos_number_outgoingdoc_continuos_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoingdoc',
            old_name='continuos_num',
            new_name='continuos_number',
        ),
    ]
